### ISSUE TITLE
Unfinished stream issue + duplicate plugin

### ISSUE THREAD

**Issue by fregante** [lisposter/gulp-cdn-ref#1]
I found that this plugin doesn't mark the task as finished so I looked for an alternative and found this, published about a month earlier: https://www.npmjs.org/package/gulp-cdn-absolute-path/

**Comment by lisposter** [comment]
@bfred-it  thank you for your feedback. And I feel so sorry, cus  that's my first gulp plugin, and I didn't tested it too much, I will check this soon!

**Comment by fregante** [comment]
Don't worry @lisposter, you don't owe me anything, :) I was just reporting and let make other users aware of the issue

**Comment by lisposter** [comment]
It's my responsibility to make it work properly. :P
